pipeline{
  agent any
  stages{
    stage('Build'){
      steps{
        echo 'please build this code'
      }
    }
    stage('Test'){
      steps{
        echo 'please test this code'
      }
    }
    stage('Deploy'){
      steps{
        echo 'please deploy this code in the dockerhub'
      }
    }
  }
}